### ISSUE TITLE
/src route includes port in return object

### ISSUE THREAD

**Issue by bakedSpaceTime** [crockk/graphical-traceroute#3]
requests to the /src route return the src node IP with ":portnum" on the end. Not sure if the port should be removed from the string or not,

**Comment by crockk** [comment]
when querying prometheus I use the src node IP to filter on the `instance` label to obtain the traceroutes, which includes the listening port of the network exporter, but i might be able to switch to the `host` label to avoid the `:portnum`? i think i can do that

metrics format:
```
mtr_rtt_seconds{host="source.node.host.name", instance="source.node.host.name:portnum", job="network_exporter_probe", name="xx", path="xx", target="xx", ttl="11", type="mean"}
```

**Comment by bakedSpaceTime** [comment]
If the port is needed to query Prometheus then we should keep it in the API parameters/responses.
Do you think it can be removed just in the UI?

Edit: removed as in, is it necessary for user to see port or can it be removed to make the drop-down more minimal.

**Comment by crockk** [comment]
```
mtr_rtt_seconds{host="source.node.host.name", instance="source.node.host.name:portnum", job="network_exporter_probe", name="xx", path="xx", target="xx", ttl="11", type="mean"}
```
I'm pretty sure the `host` and `instance` label are going to always be the same except for the `instance` label containing the port, so I should be able to use the `host` label instead for the source, no port in backend, no port in frontend 0-)

**Comment by crockk** [comment]
woah, i didnt even know you could do that with the commit ^ i didnt even do anything other than mention it in the commit message, thats super cool
